[package]
name = "genfile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.57"
argh = "0.1.7"

[profile.release]
opt-level = "s"
lto = true
strip = true