[package]
name = "genfile"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.7"
pico-args = { version = "0.4.2", features = ["combined-flags", "short-space-opt"] }
